### ISSUE TITLE
Can you make a version for the: Creality Ender 3 V2 Neo - BTT SKR Mini E3 V3, But with the stock 4.3" Ender 3 V2 Neo LCD Screen?

### ISSUE THREAD

**Issue by BIG-BRO-L** [MarlinFirmware/Configurations#1051] opened 2024-05-05 22:59 UTC
Can you make a version for the: Creality Ender 3 V2 Neo - BTT SKR Mini E3 V3, But with the stock 4.3" Ender 3 V2 Neo LCD Screen?

_Originally posted by @BIG-BRO-L in https://github.com/MarlinFirmware/Configurations/issues/1032#issuecomment-2094979429_

**Comment by thisiskeithb** [comment] 2024-05-05 23:05
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/649

**Closed as completed by thisiskeithb** 2024-05-05 23:05 UTC

**Comment by BIG-BRO-L** [comment] 2024-05-06 00:15
Would you be willing to help me? I'm kind of a noob to coding and this is my first time compiling firmware. I looked through the pin (#649) and can't find the specific marlin build version I'm looking for:

Printer: 
Ender 3 V2 Neo

Motherboard: 
Bigtreetech skr mini e3 v3

Display: 
Stock 4.3" LCD Screen

Software version: 
Marlin 2.1.x

**Comment by LeviLaswell** [comment] 2024-05-06 22:19
> Duplicate of #649
@thisiskeithb 
Where is this version for the stock lcd?

**Comment by LeviLaswell** [comment] 2024-05-06 22:21
@BIG-BRO-L 
Did you find the stock lcd version in #649?
