### ISSUE TITLE
Tronxy X5S for BTT SKR2 with TMC2209 

### ISSUE THREAD

**Issue by nicken83** [MarlinFirmware/Configurations#668] opened 2022-01-25 06:07 UTC
I'm having a really hard time configuring Marlin to this setup. Tried several compilations, always only diagonal movement in X and Y.
CoreXY is `defined`

<!--Tronxy x5s for BTT Skr2 with Te MC 2209 --

**Comment by ellensp** [comment] 2022-01-25 06:14
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23570

**Closed as completed by ellensp** 2022-01-25 06:14 UTC
