### ISSUE TITLE
[FR] Creality Ender 7

### ISSUE THREAD

**Issue by mattrayner** [MarlinFirmware/Configurations#602] opened 2021-10-29 09:20 UTC
### Description

I have an Ender 7 running the Creality 4.2.7 motherboard, it is missing some basic features, along with some very strange defaults for things like ABL. I would love to be able to compile my own firmware for it as I do with my Ender 3.

I have reached out to Creality via the info@creality.com email address (is there a better way?) to request the files, but wasn't sure if there is an alternative way to set this up?

### Configuration Details

* Manufacturer: Creality
* Model: Ender 7
* Motherboard: Creality 4.2.7

#### Additional Information

https://www.creality.com/goods-detail/creality-ender-7-3d-printer

**Comment by ellensp** [comment] 2021-10-29 09:39
It has the same touch screen as the cr-6 se which is not yet supported in standard Marlin.

**Comment by ellensp** [comment] 2021-10-29 09:40
you should do a M503 to dump basic settings

**Comment by InsanityAutomation** [comment] 2021-10-29 11:46
I've got one here and its mostly working, a few more oddities with the touchscreen to sort out. The mainboard for it is a unique board though, not a 4.2.7. I submitted the board already though.

**Comment by mattrayner** [comment] 2021-10-29 18:40
@InsanityAutomation Amazing, do you need any help at all? I'm happy to provide assistance :)

**Comment by ellensp** [comment] 2021-10-31 11:52
@InsanityAutomation I wish you would add it to real Marlin, not your fork...

**Comment by InsanityAutomation** [comment] 2021-11-01 14:34
@ellensp maybe eventually, but that discussion is better had on discord etc not here. It is however a pure ExtUI module. Drop its folder in, enable ExtUI and you're done. Its built to utilize absolutely nothing outside the API following the original intent of the system. 

There is an issue with the dgus software, every time i build the displays, at least a couple screens have been getting messed up, and idk why yet... Random and different screens every time i make a change, not even consistent. Once I figure that out we should be in good shape, Everything else is working on both the Sermoon D1 and Ender 7 that use this display.

**Comment by mattrayner** [comment] 2021-11-01 15:46
@InsanityAutomation do you have a guide to get this setup with your forks?

**Comment by InsanityAutomation** [comment] 2021-12-23 19:56
Missed the last comment here @mattrayner  however the flashing process is the same as any other DGUS display, and mainboard is just drop the bin file on an sd card and power on. - https://www.youtube.com/watch?v=SBX30GmM3Qo for flashing the LCD - https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0 for the working code

**Comment by umsmin** [comment] 2021-12-29 23:28
@InsanityAutomation you make a great work! Thank you for that. on which point are we for the Configuration.h Configuration_adv.h? Maybe similar to the Ender 6?

**Comment by InsanityAutomation** [comment] 2021-12-30 14:41
@umsmin Theyre blended together, if you search the MachineEnder7 tag in the configuration.h file youll see all the options that are set specifically for it.

**Comment by umsmin** [comment] 2021-12-30 23:47
@InsanityAutomation Ah, now I get it. It works for the first test. Only the Infoscreen is shown directly over the buttons from config screen. not in a separately screen. Thanks for all

**Comment by slashnot** [comment] 2022-01-16 23:57
@InsanityAutomation Thanks for your work. Your configuration is working good. I just selected Ender 7 BLT zm in platform.io and I got a working firmware. I also played a bit with the display firmware and I get some parts to work properly.

**Comment by thinkyhead** [comment] 2022-01-26 19:41
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:41 UTC

**Comment by fellnerse** [comment] 2022-05-16 05:41
@InsanityAutomation did you have any time/luck investigating the issue and merging this back?

**Comment by InsanityAutomation** [comment] 2022-05-16 14:17
> @InsanityAutomation did you have any time/luck investigating the issue and merging this back?

The touchscreen code is maintained in a separate repo as its still actively evolving. You can simply drop the folder into the current bugfix, and enable extensible_ui if youd like, though my code base doesnt often diverge far from bugfix.
