### ISSUE TITLE
Ender 5 plus Other Boards Options

### ISSUE THREAD

**Issue by DavidDaniels04** [MarlinFirmware/Configurations#315] opened 2020-11-06 01:46 UTC
Hello,

I was really hoping with how popular the Ender 5 Plus has become that there would both similiar options like within the Ender 3 Pro folder of other boards. Specifically btt skr 1.4 Turbo w/ 2209s and maybe even perhaps using 2130's too? lol..

**Comment by ellensp** [comment] 2020-11-06 15:10
Was looking into this. There are multiple issue to overcome.
Firstly the TFT touch screen. Firmware wise It is only compatible with the 8 bit AVR platform. It has a function SERIAL_GET_TX_BUFFER_FREE which only exists in AVR HAL 
Secondly It is normally plugged into Serial 2, pins 16 (TX) and 17 (RX) On EXP1 on a RAMPS.
There is no hardware serial port on EXP1 on the skr 1.4
There is a hardware serial port (1 on P0_15 and P0_16) on EXP2, but these are not the correct pins location. 
You would need to make a custom TFT cable

**Comment by DavidDaniels04** [comment] 2020-11-06 15:28
Yep from my understanding a rewiring of the tft would need to be done in addition to board OR an upgrade to a btt tft style tft (which is what I am currently using).. I currently have a bondtech bmg and e3d v6 hotend direct drive setup. I'm more or less surprised to see the other printers have a variety of examples using other boards and only the

**Comment by ellensp** [comment] 2020-11-06 15:35
The pins are labeled on various images, like this eg. So this helps a little.   
![back_of_tft](https://user-images.githubusercontent.com/530024/98384376-915d2400-20b2-11eb-81b6-7630356853cc.png)

**Comment by ellensp** [comment] 2020-11-10 05:40
Could you change the subject to something more specific perhaps "Ender 5 Plus, other board options".

**Comment by earth4s** [comment] 2020-11-29 04:36
I'm trying to get the SKR E3 Turbo working on my Ender 5 plus but I am using their TFT70 touchscreens instead of the stock screen. The main issue I have run into is the the BLTouch will not respond to commands. Not sure if its an issue with the nightly builds or something else.

**Comment by Cjs10mm** [comment] 2020-12-11 22:18
How hard would it be to get the info on how the TFT interfaces with the board from two users who have already made it work with non stock boards? Insanity Automation did it for Tiny Machines and DodgeDeBoulet did it for the SKR 1.4 Turbo and E3 Mini v2.

**Comment by NezSez** [comment] 2021-03-16 01:49
@earth4s For SKR 1.4 Turbo I had to switch wires on the BLTouch which came with my E5+...Creality swapped two of the wires in the group of 3 (not the black/white pair) to plug into their Creality V2.2 board that mine came with. Sry I don't remember which two for sure but I think it was NPWR and 2.0 on the Servo port. YMMV.

Newer Creality boards like the 4.2.7 and maybe the 4.2.2 seem to have new ports for the BLTouch, and newer BLTouch V3.1 Smart kits now sell with all five wires on one connector for using these ports, so they've changed things a bit. Also a friend who got the CR6-SE Kickstarter with the Creality 3D V4.5.2 board just received a replacement V4.5.3 board today; we don't know why yet.

Also, see this: #355 Ender 5 Pro now shipping with v4.2.2 mainboard which notes some changes with BLTouch

**Comment by NezSez** [comment] 2021-03-19 09:18
Given the hardware/software dependency permutations, other than having a web page/app, or local script (like `menuconfig` (et. al.) in Linux Kernel src) which could parse dependencies allowing customization with option dependency tracking, parsing #defines and displaying code comments/help/caveats, guiding the user in real time as it were, anything I can think of to optimize the current structure just ends up in "different only the same" category, or worse :)

This problem is why menuconfig was created, same for PKG leading to RPM, APT, YUM, and DNF.

I know that similar issues have been debated before many times and rejected in the past for obvious reasons [#21003 [RFC] Rename the bugfix branch](https://github.com/MarlinFirmware/Marlin/issues/21003).

Creating some example configs for the E5+ with SKR 1.4/T and various hardware will help many of course, but short of going the full-monty #define dep parsing I think it wouldn't benefit nearly as much, nor offer the ROI as the aforementioned page/app/script would. It seems like one could build off the existing sanitycheck scripts and the Marlin Autobuild to do so, and I imagine that both of those were designed with this goal in mind in addition to the primary functions they currently serve.

**Comment by thisiskeithb** [comment] 2021-03-19 14:22
> and I imagine that both of those were designed with this goal in mind

It'll get there eventually...

![image](https://user-images.githubusercontent.com/13375512/111794720-c01ab080-8883-11eb-8300-05b62b3fc484.png)

**Comment by thisiskeithb** [comment] 2022-04-11 15:25
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/649

**Closed as completed by thisiskeithb** 2022-04-11 15:25 UTC

**Comment by SteevieB** [comment] 2023-08-21 21:42
I'm trying to get the BIGTREETECH SKR Mini E3 V3.0 working on my Ender 5. Can anyone help me point me in the right direction what do i have to adjust to get it working with Marlin 2.1.2.1 based on the E3 V2.0 config files?

**Comment by thisiskeithb** [comment] 2023-08-21 21:46
@SteevieB: This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by SteevieB** [comment] 2023-08-21 21:54
@thisiskeithb Sorry, thank you very much for the helpful links!
