### ISSUE TITLE
Please Add Neptune 3 configs

### ISSUE THREAD

**Issue by COstrom7219** [MarlinFirmware/Configurations#876] opened 2023-01-03 22:12 UTC
I have an Elegoo Neptune 3 and you have configs for the Neptune 2 but I dont think I can use those right? Can you please add configs for the Neptune 3. Much appreciated thank you

**Comment by ellensp** [comment] 2023-01-03 22:22
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/649

**Closed as completed by ellensp** 2023-01-03 22:22 UTC
