### ISSUE TITLE
[BUG] Ender 5 Plus configuration.h or code problem

### ISSUE THREAD

**Issue by Poporacer** [MarlinFirmware/Configurations#491] opened 2021-05-15 04:58 UTC
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Download ver 2.0.8 and config folder from MarlinFirmware/Configurations
2. Unzip files
3. Replace configuration.h and configuration_adv.h in the Marlin folder with the ones from the Configurations-release-2.08/config/examples/creality/Ender-5 Plus folder.
4. Open the folder in VS Code (with Marlin Auto Build installed)
5. Compile project

**Expected behavior:**

The firmware to compile correctly

**Actual behavior:**
The build fails with an error stating:
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_ResumePauseAbort(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\lib\dgus\origin\DGUSScreenHandler.cpp:88:20: error: 'MKSLCD_SCREEN_PAUSE' was not declared in this scope

#### Additional Information

MKSLCD_SCREEN_PAUSE is declared in the src\lcd\ectui\lib\dgus\mks\DGUSDisplayDef.h file but that file is only included if you have  DGUS_LCD_UI_MKS defined in the configuration.h file

In the Ender-5 Plus configuration.h file, it has #define DGUS_LCD_UI_ORIGIN as the LCD Screen
I would think that the DGUS_LCD_UI_ORIGIN would be the correct LCD for a stock Ender-5 Plus, if so, then I think the reference to MKSLCD_SCREEN_PAUSE is not correct? 

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.
[Configurations.zip](https://github.com/MarlinFirmware/Configurations/files/6481880/Configurations.zip)

**Comment by ellensp** [comment] 2021-05-15 05:45
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21576

**Closed as completed by ellensp** 2021-05-15 05:45 UTC
