### ISSUE TITLE
[FR] Support for Creality board v24S1 v301 for Ender 3 S1

### ISSUE THREAD

**Issue by leofaoro** [MarlinFirmware/Configurations#645] opened 2021-12-30 05:37 UTC
Hello
I’d love to install a custom Marlin FW on my new Ender 3. A few annoying things have been disabled by default. 
Anyway the board is new, powered by a STM32F103RCT6. I tried to trace the pins but couldn’t do it properly. 

Would greatly appreciate an official config. 
thanks

**Comment by ellensp** [comment] 2021-12-30 05:55
![177D9D10F94E5C24!163305](https://user-images.githubusercontent.com/530024/147725493-45335090-2086-4a7f-b78b-d77c055fa3c3.jpg)
![177D9D10F94E5C24!163295](https://user-images.githubusercontent.com/530024/147725580-7c26dd64-d306-432f-afb7-8bfe39c8db5b.jpg)

**Comment by leofaoro** [comment] 2021-12-30 06:42
Yeah that's my post on Reddit :) Here are a couple more that are more clear, also with the back of the board.

![20211230_040841358_iOS](https://user-images.githubusercontent.com/1944817/147727961-16443772-6c94-4821-b44c-c4d4d7ffec59.jpg)
![20211230_040851248_iOS](https://user-images.githubusercontent.com/1944817/147727963-96ffb131-c464-459b-adf9-b856bc9c7623.jpg)

**Comment by leofaoro** [comment] 2021-12-31 00:59
HEATER BED is on pin 63 (VSS_3). Also for the CR-Touch,  pin 2 (PC13) = servo pin, pin 3 (PC14) = probe pin. Updated Peter's spreadsheet.

**Comment by ellensp** [comment] 2021-12-31 08:54
"HEATER BED is on pin 63 (VSS_3)" 
That is a gnd pin.  That cannot be correct 

The normal arrangement for a heated bed is the +v is permanently connected but the -v is connected via a mosfet
When the bed is off both bed pins are at a positive voltage so no current flows. When the  bed is turned on the -ve leg is connected to gnd allowing current to flow.

**Comment by leofaoro** [comment] 2022-01-01 00:43
> "HEATER BED is on pin 63 (VSS_3)" That is a gnd pin. That cannot be correct
> 
> The normal arrangement for a heated bed is the +v is permanently connected but the -v is connected via a mosfet When the bed is off both bed pins are at a positive voltage so no current flows. When the bed is turned on the -ve leg is connected to gnd allowing current to flow.

Oh no, I was tracing the wrong leg then. It went from the STM32 to a resistor, to some logic level chip, then out to the mosfet, then to the bed....

**Comment by leofaoro** [comment] 2022-01-03 02:34
Ok I have the printer sort of working. Issues:
- The extruder fan does not turn on. 
- the part cooling fan makes a strange sound, not sure if it's PWM related. It works and is controllable
- the screen does not work

Here's my commit on the my 2.0.9.3 fork (not sure I'm doing this the right way, first time contributing) 
https://github.com/leofaoro/Marlin/commits/2.0.x

**Comment by ellensp** [comment] 2022-01-03 02:44
Documenting from discord chat. 
The screen does not seem to be the same as a e3v2 screen

This is the screen in question

![177D9D10F94E5C24!163345](https://user-images.githubusercontent.com/530024/147896368-eb17d3d0-f5cc-4bb1-8967-9ecddc6a94d1.jpg)

It is using a Allwinner F1C100s as is CPU

From the updated source provided from creality 

[Ender-3s1-hw24s1_301-sw-V1.0.5_C-CRTouch.zip](https://github.com/MarlinFirmware/Configurations/files/7800175/Ender-3s1-hw24s1_301-sw-V1.0.5_C-CRTouch.zip)

It has a DWIN_SET folder, with files for the e3v2 screen, but it also has a private folder which contains the same information as the DWIN_SET but in a different format.

Current thinking is that this new lcd uses the private directory for its data.
This screen is not compatible with Marlin at this time as marlin expects the Marlin DWIN_SET

**Comment by leofaoro** [comment] 2022-01-03 06:54
Some progress. Indeed the display will update only if provided a "private" folder. I tried the DWIN_SET from the E3V2 config example in Marlin, renamed it to "private" it took but only blank screen. Also tried the "private" folder provided in Creality's latest firmware update (1.0.5) above, and constantly shows the splash page "Creality". 

Also confirmed pinout is exactly the same for both LCD screens.

**Comment by leofaoro** [comment] 2022-01-03 16:42
Extruder fan identified and added to pins file + config adv. Working.
https://github.com/leofaoro/Marlin/commit/5e8f206a15270e267340702035c9c9a2b4edb69e

**Comment by Geo-Warrior** [comment] 2022-01-06 01:43
Hi. I'm probably better suited as a lurker here as a lot of this is over my head. If there's anything I can help with, just throw it out there and I'll do my best. Thanks for the work you're doing.

**Comment by skilly00** [comment] 2022-01-18 16:38
What is left to do on this project?  Leo has it been finished or do you need help with anything?  I have this printer and would be happy to help id anything you still have outstanding.

**Comment by leofaoro** [comment] 2022-01-18 16:45
> What is left to do on this project? Leo has it been finished or do you need help with anything? I have this printer and would be happy to help id anything you still have outstanding.

Hey! The screen is still not working. It’s totally undocumented and I don’t have the skills to reverse engineer it. Everything else seems to be working.

**Comment by skilly00** [comment] 2022-01-18 17:18
Ok cool.  well maybe I'm missing something but can't you just include the Firmware from the official files for the screen?

**Comment by leofaoro** [comment] 2022-01-18 18:20
> Ok cool. well maybe I'm missing something but can't you just include the Firmware from the official files for the screen?

Nope. Doesn't work.

**Comment by mriscoc** [comment] 2022-01-18 19:27
> > Ok cool. well maybe I'm missing something but can't you just include the Firmware from the official files for the screen?
> 
> Nope. Doesn't work.

I don't have a Ender3S1 but have some interest in try to develop something for that printer. We need to know exactly what mean "Doesn't work", the screen is permanent in black, the display shows boot screen and then black, the screen shows a bad user interface, etc.

**Comment by leofaoro** [comment] 2022-01-18 19:33
Fair. Currently the screen turns on and stays on the boot screen. The button when pressed does beep. That’s about all it does. If someone has an ender 3 v2 screen and wants to try that could be helpful.

**Comment by mriscoc** [comment] 2022-01-18 19:40
OK, if the boot background is there, then that only ensures that the display is correctly energized and reset. Could be interesting to know if the printer works fine using Octoprint and last Marlin bugfix, for example.

**Comment by leofaoro** [comment] 2022-01-18 20:02
> OK, if the boot background is there, then that only ensures that the display is correctly energized and reset. Could be interesting to know if the printer works fine using Octoprint and last Marlin bugfix, for example.

Yes. It works using my pins file and connects/prints with Octoprint. As I said, the only thing that is not working is the screen.

**Comment by mriscoc** [comment] 2022-01-18 20:24
> > OK, if the boot background is there, then that only ensures that the display is correctly energized and reset. Could be interesting to know if the printer works fine using Octoprint and last Marlin bugfix, for example.
> 
> Yes. It works using my pins file and connects/prints with Octoprint. As I said, the only thing that is not working is the screen.

Then the next thing is to identify is the serial link between the mainboard and the display.

**Comment by leofaoro** [comment] 2022-01-18 20:27
> Then the next thing is to identify is the serial link between the mainboard and the display.

Yes, and that goes beyond my skills :)

**Comment by mriscoc** [comment] 2022-01-18 20:31
I need a S1 here, :-D

**Comment by skilly00** [comment] 2022-01-18 23:39
How would one go about identifying the serial link?  I have the display and am happy to help if you can point me to some kind of guide.  I have a CC Debugger would that work?

**Comment by mriscoc** [comment] 2022-01-19 01:46
> How would one go about identifying the serial link? I have the display and am happy to help if you can point me to some kind of guide. I have a CC Debugger would that work?

I don't know if the correct serial interface in the board was enabled in the @leofaoro files.   A CC Debugger could help. I'm assuming that the firmware compilated is issuing some commands to the display at the start up, that serial activity could be noted by the debugging device if the firmware is using the correct pin.

**Comment by skilly00** [comment] 2022-01-19 01:55
Ok, @leofaoro said above that it was using the same pins.  They are labeled on the screenshot provided by @ellensp but I can't find a screenshot from the V2 to confirm they are the same.   So to be clear I should be hooking up to the 10 pin from the printer at boot to see if its getting the commands your thinking are sent.

**Comment by ellensp** [comment] 2022-01-19 02:05
Ithe pins are the same
<img src="https://user-images.githubusercontent.com/2153744/88888513-0679bb80-d271-11ea-95be-4aaff319f514.jpg">

I suspect this is a dwni clone, using dwin protocol.
But the way you update its data is different, as it is not runing DWIN os

**Comment by mriscoc** [comment] 2022-01-19 02:06
The problem is to know if the firmware is using the correct serial port and pin enables of the display interface in the S1 SoC. @leofaoro, the display beeps when the enconder is pressed? The display beeps when you send a M300?

**Comment by leofaoro** [comment] 2022-01-19 05:04
I went ahead and mapped the pins to the LCD ribbon cable. See below. 

DOUT = PA3
DIN = PA2
BEEP = PB13
ENT = PB14
A = PB15
B = PB12

I don't know what these mean in terms of mapping to Marlin pins. I know there's BTN_ENC, BTN_EN1, BTN_EN2, BEEPER_PIN listed for DWIN_E3V2. 

![2022-01-18 21_01_15-20220103_170559906_iOS jpg ‎- Photos](https://user-images.githubusercontent.com/1944817/150067248-5a73bf0c-3f64-4416-b2a9-28542dab91cf.png)

**Comment by leofaoro** [comment] 2022-01-19 05:06
> The problem is to know if the firmware is using the correct serial port and pin enables of the display interface in the S1 SoC. @leofaoro, the display beeps when the enconder is pressed? The display beeps when you send a M300?

the display beeps when buttons is pressed yes. Haven't tested M300.

**Comment by ellensp** [comment] 2022-01-19 05:09
PA3/PA3 is USART2_TX/USART2_RX  ie uart port 2

**Comment by mriscoc** [comment] 2022-01-19 05:20
> PA3/PA3 is USART2_TX/USART2_RX ie uart port 2

That is an advance, in the Ender3v2 the LCD Serial port is 3:
```cpp
#define LCD_SERIAL_PORT 3
```
Then, @leofaoro change that to 2 in `Conditionals_LCD.h` and test.

**Comment by skilly00** [comment] 2022-01-19 06:10
not sure if this helps at all but I just put the display from the s1 into a v2 and it seemed to work just fine.  I went through all the menus and had full functionality.

**Comment by mriscoc** [comment] 2022-01-19 06:13
> not sure if this helps at all but I just put the display from the s1 into a v2 and it seemed to work just fine. I went through all the menus and had full functionality.

That helps! then the serial speed, protocol and icon assets are the same!

**Comment by ellensp** [comment] 2022-01-19 06:17
As I already said its is a dwin clone, using dwin protocol.
but asset binary are in a different format.
It uses assets from the private directory, not the dwin_set
see example in https://github.com/MarlinFirmware/Configurations/files/7800175/Ender-3s1-hw24s1_301-sw-V1.0.5_C-CRTouch.zip

**Comment by mriscoc** [comment] 2022-01-19 06:20
But the test from @skilly00 confirm that, I didn't have a confirmation before or at less I didn't see it.

**Comment by ellensp** [comment] 2022-01-19 06:22
Its clear to me, as the official update doesn't have two sets of controller firmware only two sets of assets. So both
 screens must be using same protocol (or they support both in one firmware and detect the screen, but that would double their dev time, and a larger firmware)

**Comment by ellensp** [comment] 2022-01-19 06:28
I think efforts should be directed at finding how to covert dwin_set files to private files 
Ie try an port Marin dwin_set over

**Comment by mriscoc** [comment] 2022-01-19 09:08
Ok, please test with this repo: https://github.com/mriscoc/Marlin_Ender3S1
Precompiled binary here: https://github.com/mriscoc/Marlin_Ender3S1/releases/latest
Please check if the display is working now. Caution this is a Beta (or Alpha) version.

**Comment by leofaoro** [comment] 2022-01-19 15:54
> Ok, please test with this repo: https://github.com/mriscoc/Marlin_Ender3S1
> Precompiled binary here: https://github.com/mriscoc/Marlin_Ender3S1/releases/latest
> Please check if the display is working now. Caution this is a Beta (or Alpha) version.

Screen works!!  Haven’t tested anything else but assuming you use my initial files, should be all good. Will test more later.

**Comment by skilly00** [comment] 2022-01-19 15:57
Great news!  Thank you @mriscoc @leofaoro and @ellensp for all the work done.  I'm finishing a print on mine around 2PM EST and will load it as well to test.

**Comment by mriscoc** [comment] 2022-01-19 16:01
@leofaoro did you test the changes to see if the display works?

**Comment by mriscoc** [comment] 2022-01-19 16:01
Excellent! You are welcome

**Comment by leofaoro** [comment] 2022-01-19 18:51
Thanks @mriscoc for creating the PR. I wouldn't know how to do that :)

**Comment by skilly00** [comment] 2022-01-20 02:31
Sorry a bit later than I said but I can confirm it is working as expected with your recompiled version.  I did a few prints and bed leveling, local and with OctoPrint and all has come out fine!

**Comment by mriscoc** [comment] 2022-01-20 02:35
> Sorry a bit later than I said but I can confirm it is working as expected with your recompiled version. I did a few prints and bed leveling, local and with OctoPrint and all has come out fine!

What about the BLTouch and filament runout sensor?

**Comment by skilly00** [comment] 2022-01-20 02:38
It has a CR touch but yes that worked with the auto leveling on the screen and auto Z offset as well as in OctoPrint with Unified Gcode in bedlevelvisualizer plugin.  I didn't test the runout sensor but can do that now.

**Comment by mriscoc** [comment] 2022-01-20 02:40
> It has a CR touch but yes that worked with the auto leveling on the screen and auto Z offset as well as in OctoPrint with Unified Gcode in bedlevelvisualizer plugin. I didn't test the runout sensor but can do that now.

There is an end-stop diagnostics page in the Advanced menu. When the filament is inserted, you get a TRIGGERED status:  
  
![endstops-diagnostic](https://user-images.githubusercontent.com/2745567/150262445-d028e457-b39b-4975-8b37-bddb34a440b3.jpg)

**Comment by skilly00** [comment] 2022-01-20 02:46
Yeah then it is working correctly.  I saw that when running through the menu after loading the first time.  I can also say it says Open when the filament is removed.

**Comment by mriscoc** [comment] 2022-01-20 02:48
> Yeah then it is working correctly. I saw that when running through the menu after loading the first time. I can also say it says Open when the filament is removed.

Thank you for your report!

**Comment by Wassabichan** [comment] 2022-01-20 13:38
i have testet it and recognized the my raspberry isn`t working with the firmware
is this a bug or not in the code yet?

**Comment by mriscoc** [comment] 2022-01-20 14:04
> i have testet it and recognized the my raspberry isn`t working with the firmware is this a bug or not in the code yet?

Set the baud speed to AUTO or 250000 use this wiki to configure Octoprint: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Octoprint

**Comment by Wassabichan** [comment] 2022-01-20 14:12
i did, and then i wannt to report that my screen was only blue and black and the screen output  wasn`t working proplably.
it isn't like i want to say it`s trash  i just wanna give feedback and i wannja help were i can

**Comment by skilly00** [comment] 2022-01-20 15:56
@mriscoc I didn't report it because I figured I needed to change my start gcode most likely but when I use Octoprint, after homing/heating and leveling the printer hangs for 5 or so min before it starts.  This could be something in my start code I haven't dug into but if @Wassabichan is having issues with OctoPrint it may be related to the Firmware.

**Comment by Wassabichan** [comment] 2022-01-20 17:29
ând is it normal thet the interface is only blue with dark writing? or is only mine like that?

**Comment by mriscoc** [comment] 2022-01-20 17:38
> @mriscoc I didn't report it because I figured I needed to change my start gcode most likely but when I use Octoprint, after homing/heating and leveling the printer hangs for 5 or so min before it starts. This could be something in my start code I haven't dug into but if @Wassabichan is having issues with OctoPrint it may be related to the Firmware.

Please confirm that is not the warm-up time of the bed/nozzle

**Comment by mriscoc** [comment] 2022-01-20 17:39
> ând is it normal thet the interface is only blue with dark writing? or is only mine like that?

Please post an image.

**Comment by Wassabichan** [comment] 2022-01-20 18:16
sry but i can`t because i already have the normal firmware on it again

**Comment by Wassabichan** [comment] 2022-01-20 18:17
but i can do it tomorrow, if it can help

**Comment by Sebazzz** [comment] 2022-01-20 19:04
@mriscoc I suggest the following diff to your config:

```diff
diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
index 091d7e134f..208447043b 100644
--- a/Marlin/Configuration.h
+++ b/Marlin/Configuration.h
 /**
@@ -123,7 +123,7 @@
  *
  * :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000]
  */
-#define BAUDRATE 250000  // MRiscoC increase serial performace
+#define BAUDRATE 115200  // MRiscoC increase serial performace
 #define BAUD_RATE_GCODE     // Enable G-code M575 to set the baud rate  // MRiscoC Enables change the baudrate
 
 /**
@@ -1198,7 +1198,7 @@
  *     |    [-]    |
  *     O-- FRONT --+
  */
-#define NOZZLE_TO_PROBE_OFFSET { -37, -39, -3 }  // Ender3S1 Configs
+#define NOZZLE_TO_PROBE_OFFSET { -37, -39, -3.25 }  // Ender3S1 Configs
 
 // Most probes should stay away from the edges of the bed, but
 // with NOZZLE_AS_PROBE this can be negative for a wider probing area.
@@ -1401,8 +1401,8 @@
 #define Y_BED_SIZE 230  // MRiscoC Max usable bed size
 
 // Travel limits (mm) after homing, corresponding to endstop positions.
-#define X_MIN_POS 0
-#define Y_MIN_POS 0
+#define X_MIN_POS -5
+#define Y_MIN_POS -5
 #define Z_MIN_POS 0
 #define X_MAX_POS 248  // MRiscoC Stock physical limit
 #define Y_MAX_POS 231  // MRiscoC Stock physical limit
@@ -1574,7 +1574,7 @@
  * leveling immediately after G28.
  */
 //#define RESTORE_LEVELING_AFTER_G28
-//#define ENABLE_LEVELING_AFTER_G28
+#define ENABLE_LEVELING_AFTER_G28
 
 /**
  * Auto-leveling needs preheating
```

- Baudrate: My device didn't support baudrate 250000, besides it is unnecessarily high (unless you really need to transfer files over serial)
- `ENABLE_LEVELING_AFTER_G28`: Always enable bed leveling mesh
- X_MIN_POS / Y_MIN_POS: Otherwise X=0,Y=0 were outside the bed

May I request the source of your binary build btw, as per GPL?

**Comment by leofaoro** [comment] 2022-01-20 19:14
Everything seems to be working for me. 
The only minor issue is the fonts seem to have a different background so there are a few pixels around the font where the antialiasing isn't clear. Obviously minor.

**Comment by Wassabichan** [comment] 2022-01-20 19:21
i`m gonna take pictures tomorrow, but i had the problem that there weren't any pictures on the screen, just blank boxes and i couldn't see on what box i am

**Comment by Wassabichan** [comment] 2022-01-20 19:23
i could do them right now but i don't know how to get back the M503 Data on the printer

**Comment by mriscoc** [comment] 2022-01-20 19:24
@Sebazzz the source is in the S1 repo

**Comment by mriscoc** [comment] 2022-01-20 19:47
> 



> Everything seems to be working for me. The only minor issue is the fonts seem to have a different background so there are a few pixels around the font where the antialiasing isn't clear. Obviously minor.

@leofaoro, are you using the binary file?

**Comment by Sebazzz** [comment] 2022-01-20 19:53
> @Sebazzz the source is in the S1 repo

Yes, but I think you forgot to commit a file because it's not compiling for me. Can you send it directly if you don't want to publish the file?

**Comment by leofaoro** [comment] 2022-01-20 19:58
> @leofaoro, are you using the binary file?

no i compiled using the VSCode extension

**Comment by mriscoc** [comment] 2022-01-20 19:59
> > @leofaoro, are you using the binary file?
> 
> no i compiled using the VSCode extension

You compile from my repo? https://github.com/mriscoc/Marlin_Ender3S1

**Comment by leofaoro** [comment] 2022-01-20 20:01
> 

yes sir, the one and only!

**Comment by mriscoc** [comment] 2022-01-20 20:02
> yes sir, the one and only!

Thank you, then the repo is ok

**Comment by mriscoc** [comment] 2022-01-20 20:07
> > @Sebazzz the source is in the S1 repo
> 
> Yes, but I think you forgot to commit a file because it's not compiling for me. Can you send it directly if you don't want to publish the file?

The repo is ok
![image](https://user-images.githubusercontent.com/2745567/150413894-c9e39279-8d57-463e-a1f4-fd213dbfaa94.png)

![image](https://user-images.githubusercontent.com/2745567/150413940-b7f870c5-801b-4c50-9561-9c86adf5e87c.png)

**Comment by Wassabichan** [comment] 2022-01-20 20:09
i have a few photos for u, auto bedleveling seems fine, but the z offset isn't constant and all images are gone
![1642708908424](https://user-images.githubusercontent.com/98101131/150414190-ea9b5ebf-6eb8-461a-bc2a-50b90d29dff9.jpg)
![1642708971785](https://user-images.githubusercontent.com/98101131/150414196-b21432a8-62ab-4981-9c14-f694000b7ced.jpg)
![1642709002934](https://user-images.githubusercontent.com/98101131/150414202-5365b80d-71a1-4a62-8140-883444373b5f.jpg)
![1642709022164](https://user-images.githubusercontent.com/98101131/150414208-e4d3d495-c944-40f2-b347-72276713bda3.jpg)
![1642709119978](https://user-images.githubusercontent.com/98101131/150414211-3149aab7-c1cf-4480-909d-72d4cd08fed4.jpg)

**Comment by skilly00** [comment] 2022-01-20 20:11
> > @mriscoc I didn't report it because I figured I needed to change my start gcode most likely but when I use Octoprint, after homing/heating and leveling the printer hangs for 5 or so min before it starts. This could be something in my start code I haven't dug into but if @Wassabichan is having issues with OctoPrint it may be related to the Firmware.
> 
> Please confirm that is not the warm-up time of the bed/nozzle

Yes it was just settings.  I do have artifacts on some lettering but all the graphics work

**Comment by mriscoc** [comment] 2022-01-20 20:13
> i have a few photos for u, auto bedleveling seems fine, but the z offset isn't constant !

@Wassabichan, are you using the default S1 display?

Sorry @leofaoro and @skilly00 could you confirm the failure with the icons that @Wassabichan have?

**Comment by mriscoc** [comment] 2022-01-20 20:14
The @Wassabichan failure is classical that have an incompatible Display asset.

**Comment by leofaoro** [comment] 2022-01-20 20:14
> > i have a few photos for u, auto bedleveling seems fine, but the z offset isn't constant !
> 
> @Wassabichan, are you using the default S1 display?
> 
> Sorry @leofaoro and @skilly00 could you confirm the failure with the icons that @Wassabichan have?

I have all icons working, but i updated also with the latest "private" files submitted by creality.

**Comment by Wassabichan** [comment] 2022-01-20 20:15
@leofaoro yes it is the original
how did you get the latest files?

**Comment by skilly00** [comment] 2022-01-20 20:16
I used the compiled version and here are screenshots of mine.  You can see the grain around Confirm and progress bar being the only issue I have with the display. ![image](https://user-images.githubusercontent.com/29295394/150415238-9a2216a3-c112-4dd6-9c64-af0a98c23304.jpeg)![image](https://user-images.githubusercontent.com/29295394/150415293-30638414-988b-40ff-ae09-af55dcdfed82.jpeg)![image](https://user-images.githubusercontent.com/29295394/150415307-25392c73-7043-4451-99b2-dbb625233212.jpeg)![image](https://user-images.githubusercontent.com/29295394/150415315-7c45e926-9419-4b17-80bd-b06866febed8.jpeg)

**Comment by Wassabichan** [comment] 2022-01-20 20:17
where did you get them?

**Comment by skilly00** [comment] 2022-01-20 20:20
> where did you get them?

https://github.com/mriscoc/Marlin_Ender3S1/releases/tag/20220119  
I just put all 3 files on an SD and rebooted(I don't think you need anything but the BIN file).  Nothing else was on the card.  The way @mriscoc got around our issue with the Display was not to use any other assets but what was already on the display.

**Comment by Wassabichan** [comment] 2022-01-20 20:26
so with the newest beta version the images are back

**Comment by Wassabichan** [comment] 2022-01-20 20:26
and octoprint is working, too

**Comment by Wassabichan** [comment] 2022-01-20 20:49
the only problem now is that i still can`t turn off the printer via octoprint even with host_prompt_support and host_action_commands enabled

**Comment by mriscoc** [comment] 2022-01-20 21:23
> I used the compiled version and here are screenshots of mine. You can see the grain around Confirm and progress bar being the only issue I have with the display. 

Seems that this S1 display firmware processes the icons transparency in a different way that the original DWIN display for the V2

**Comment by leofaoro** [comment] 2022-01-21 02:54
I tested just now and the icons work for the "Creality LCD Enhanced" option but not for Jyers.

**Comment by Wassabichan** [comment] 2022-01-21 12:48
the heating safety system got triggered on mine and the nozzle heating isn`t stable while printing, it gets around 5 degrees over the temp, and then around 5 degrees underneath the normal printtemp

**Comment by Wassabichan** [comment] 2022-01-21 12:50
even if i just preheat it

**Comment by skilly00** [comment] 2022-01-21 15:01
I am having the same issue maintaining a tight temp. Seems to be about a 10degree swing @Wassabichan @mriscoc ![image](https://user-images.githubusercontent.com/29295394/150557246-ce3854ae-b25d-4c5e-94e7-ecd13d37d449.jpeg)

**Comment by Wassabichan** [comment] 2022-01-21 16:00
i found the solution, see https://www.youtube.com/watch?v=qCtL0Yd_w0I&t=441s&ab_channel=TeachingTech

**Comment by mriscoc** [comment] 2022-01-21 16:24
> I am having the same issue maintaining a tight temp. Seems to be about a 10degree swing @Wassabichan @mriscoc ![image](https://user-images.githubusercontent.com/29295394/150557246-ce3854ae-b25d-4c5e-94e7-ecd13d37d449.jpeg)

You must to do a PID, please after doing the PID for hotend and bed, post your K results for add them to the firmware as default values. Please @leofaoro give me your PID results also.

**Comment by Sebazzz** [comment] 2022-01-21 16:27
> > > @Sebazzz the source is in the S1 repo
> > 
> > 
> > Yes, but I think you forgot to commit a file because it's not compiling for me. Can you send it directly if you don't want to publish the file?
> 
> The repo is ok ![image](https://user-images.githubusercontent.com/2745567/150413894-c9e39279-8d57-463e-a1f4-fd213dbfaa94.png)
> 
> ![image](https://user-images.githubusercontent.com/2745567/150413940-b7f870c5-801b-4c50-9561-9c86adf5e87c.png)

I miss gcode_preview.h which is what I'm trying to compile - you may have accidentally forgot to add it in git. 

If not, do you have an e-mail address I can send a mail to to request the source code?

**Comment by mriscoc** [comment] 2022-01-21 16:29
> > > > @Sebazzz the source is in the S1 repo
> > > 
> > > 
> > > Yes, but I think you forgot to commit a file because it's not compiling for me. Can you send it directly if you don't want to publish the file?
> > 
> > 
> > The repo is ok ![image](https://user-images.githubusercontent.com/2745567/150413894-c9e39279-8d57-463e-a1f4-fd213dbfaa94.png)
> > ![image](https://user-images.githubusercontent.com/2745567/150413940-b7f870c5-801b-4c50-9561-9c86adf5e87c.png)
> 
> I miss gcode_preview.h which is what I'm trying to compile - you may have accidentally forgot to add it in git.
> 
> If not, do you have an e-mail address I can send a mail to to request the source code?

It is not available yet for the S1, the binary file also does not have it.

**Comment by Sebazzz** [comment] 2022-01-21 16:34
> > > > > @Sebazzz the source is in the S1 repo
> > > > 
> > > > 
> > > > Yes, but I think you forgot to commit a file because it's not compiling for me. Can you send it directly if you don't want to publish the file?
> > > 
> > > 
> > > The repo is ok ![image](https://user-images.githubusercontent.com/2745567/150413894-c9e39279-8d57-463e-a1f4-fd213dbfaa94.png)
> > > ![image](https://user-images.githubusercontent.com/2745567/150413940-b7f870c5-801b-4c50-9561-9c86adf5e87c.png)
> > 
> > 
> > I miss gcode_preview.h which is what I'm trying to compile - you may have accidentally forgot to add it in git.
> > If not, do you have an e-mail address I can send a mail to to request the source code?
> 
> It is not available yet for the S1, the binary file also does not have it.

Ok 🙃 Anything I can help to make it compatible? I know my way around.

**Comment by mriscoc** [comment] 2022-01-21 17:00
> Ok 🙃 Anything I can help to make it compatible? I know my way around.

Request to Creality to send me a S1 😁

**Comment by Wassabichan** [comment] 2022-01-21 17:18
i just noticed that my the printer thinks it's print bed size is 230x230x250 but the ender 3 S1 does just have a 220x220x270 print size
any solutions?

**Comment by Sebazzz** [comment] 2022-01-21 17:18
> > Ok 🙃 Anything I can help to make it compatible? I know my way around.
> 
> Request to Creality to send me a S1 😁

No I meant, I have unit here, if you send it then I can attempt to make it work 😉

**Comment by mriscoc** [comment] 2022-01-21 17:50
> i just noticed that my the printer thinks it's print bed size is 230x230x250 but the ender 3 S1 does just have a 220x220x270 print size any solutions?

I must to correct that in the configuration files.

**Comment by Sebazzz** [comment] 2022-01-21 17:51
End-to-end the build plate is 230 so I think it is fine.

**Comment by Wassabichan** [comment] 2022-01-21 17:55
yea but 20 cm hight is lost

**Comment by mriscoc** [comment] 2022-01-21 18:53
I release some fixes:
- Fix Probe Z offset
- Fix Z Max position
- Fix Buttons background
- Fix Progress bar background

**Comment by mriscoc** [comment] 2022-01-21 19:52
> yea but 20 cm hight is lost

Was 20 **mm** = 2 cm, but it is correct now.

**Comment by skilly00** [comment] 2022-01-21 20:21
Here are the PID values I got at 230 with 10 cycles.
Recv: #define DEFAULT_Kp 12.83
Recv: #define DEFAULT_Ki 0.76
Recv: #define DEFAULT_Kd 53.90

**Comment by skilly00** [comment] 2022-01-21 20:38
> I release some fixes:
> 
>     * Fix Probe Z offset
> 
>     * Fix Z Max position
> 
>     * Fix Buttons background
> 
>     * Fix Progress bar background

Still getting issues with the Button Background and and progress bars on new compiled version.  Z height is fixed and I'm not sure what was wrong with the probe offset so can't say on that. mine is -2.66 with the stock bed and this is over -3

**Comment by Wassabichan** [comment] 2022-01-21 20:59
can u link the new version?

**Comment by skilly00** [comment] 2022-01-21 21:20
Same location as the last one.  https://github.com/mriscoc/Marlin_Ender3S1/releases

**Comment by mriscoc** [comment] 2022-01-21 22:25
> Still getting issues with the Button Background and and progress bars on new compiled version. Z height is fixed and I'm not sure what was wrong with the probe offset so can't say on that. mine is -2.66 with the stock bed and this is over -3

Can you please post a capture of your info page?

**Comment by skilly00** [comment] 2022-01-22 00:11
> > Still getting issues with the Button Background and and progress bars on new compiled version. Z height is fixed and I'm not sure what was wrong with the probe offset so can't say on that. mine is -2.66 with the stock bed and this is over -3
> 
> 
> 
> Can you please post a capture of your info page?
> 
> 

![image](https://user-images.githubusercontent.com/29295394/150615632-bf0aec1f-6aed-4c3b-aa4f-8e77b8f58e49.jpeg)

**Comment by mriscoc** [comment] 2022-01-22 01:00
Sorry, but I'm forced to stop the development here. In the future I will post only in my repository. Thank you for all your help.

**Comment by skilly00** [comment] 2022-01-22 03:00
Ok, thank you for all the progress you've made so far.

**Comment by mriscoc** [comment] 2022-01-22 04:23
> Ok, thank you for all the progress you did make! Anyone know what happened? Sorry I am aware of the exact process for pull requests as a non developer but I'm thinking we need to submit a PR to the bug fix branch to get this config added to the main branch after review. Anyone watching this thread know how to do that? I think its important since @mriscoc isn't supporting it anymore.

I'm moving the support to my repository: https://github.com/mriscoc/Ender3S1 there you can do PR and post issues

**Comment by thinkyhead** [comment] 2022-01-26 00:33
Fixed up and merged. Thanks @mriscoc !

**Closed as completed by thinkyhead** 2022-01-26 00:33 UTC

**Comment by EvilGremlin** [comment] 2022-02-04 12:49
Can someone make SPI flash dump? Looking at ttf font, i suspect it actually runs linux, so i'm curious to poke around.

**Comment by Sebazzz** [comment] 2022-02-04 13:08
It has the [F1C100s](https://linux-sunxi.org/F1C100s) so I think you may be right. No promises, but I'Il check if [these tools](https://github.com/linux-sunxi/sunxi-tools) can help me with an SPI flash dump.

**Comment by Sebazzz** [comment] 2022-02-04 15:34
> It has the [F1C100s](https://linux-sunxi.org/F1C100s) so I think you may be right. No promises, but I'Il check if [these tools](https://github.com/linux-sunxi/sunxi-tools) can help me with an SPI flash dump.

They can - but refer to an USB connection. The ribbon cable connector does have a 5V/GND/Data in/Data Out but that isn't USB - is it?

**Comment by ellensp** [comment] 2022-02-04 15:59
From the image and the datasheat, the connector J3, is USB 

Pin 68 is USB-DM
Pin 69 is USB-DP

so the 3 pins on J3 left to right seem to be USB-DM, USB-DP and gnd

**Comment by EvilGremlin** [comment] 2022-02-04 17:38
I bet it's DFU port, and J2 is DFU switch.

**Comment by mriscoc** [comment] 2022-03-01 03:25
@leofaoro please could you confirm what pin is connected to the Z limit interface?

![image](https://user-images.githubusercontent.com/2745567/156099116-dd6853d7-8b0f-4972-a933-47d09b57427e.png)

**Comment by leofaoro** [comment] 2022-03-02 17:11
Hi Miguel. I don't think I mapped the Z limit interface pins.

**Comment by mriscoc** [comment] 2022-03-02 17:37
> Hi Miguel. I don't think I mapped the Z limit interface pins.


Thank you. With the release of the official Creality firmware, all pins are correct now. I was able to compile a Manual mesh version for people that the CRTouch is not working correctly.

Here are the configuration files completed for the S1: https://github.com/mriscoc/Marlin_Configurations/tree/main/Ender%203S1

**Comment by leofaoro** [comment] 2022-03-02 17:40
> > Hi Miguel. I don't think I mapped the Z limit interface pins.
> 
> Thank you. With the release of the official Creality firmware, all pins are correct now. I was able to compile a Manual mesh version for people that the CRTouch is not working correctly.
> 
> Here are the configuration files completed for the S1: https://github.com/mriscoc/Marlin_Configurations/tree/main/Ender%203S1

Thanks again for all your work. Now only if we could have linear advance on this board with Marlin...

**Comment by mriscoc** [comment] 2022-03-02 17:42
> Thanks again for all your work. Now only if we could have linear advance on this board with Marlin...

I think that it is necessary to have a hardware mod for the board to change the drivers from standalone to UART mode.

**Comment by leofaoro** [comment] 2022-03-02 17:50
> I think that it is necessary to have a hardware mod for the board to change the drivers from standalone to UART mode.

that's my understanding also from my readings. I could try it, but it's high risk of wrecking the board, so not worth it to me. Might as well just get an opensource board but with all the ribbon cables of the S1 you'd also need perhaps a breakout board.

**Comment by mriscoc** [comment] 2022-08-09 00:16
Hi @leofaoro I saw in the Creality official repository that FIL_RUNOUT_STATE in Configuration.h file is LOW, but in our initial research we set that value as HIGH. Can you confirm if the Stock S1 uses LOW or HIGH value for its filament sensor?

**Comment by leofaoro** [comment] 2022-08-09 00:47
> Hi @leofaoro I saw in the Creality official repository that FIL_RUNOUT_STATE in Configuration.h file is LOW, but in our initial research we set that value as HIGH. Can you confirm if the Stock S1 uses LOW or HIGH value for its filament sensor?

It should trigger on LOW. 

Leo

**Comment by mriscoc** [comment] 2022-08-09 00:54
> It should trigger on LOW.
> 
> Leo

Thanks for your reply, so, the Marlin sample configs also have that error:

https://github.com/MarlinFirmware/Configurations/blob/c771f3f732204a8ea97a4f46092142e7601871ab/config/examples/Creality/Ender-3%20S1/STM32F1/Configuration.h#L1778

**Comment by mriscoc** [comment] 2022-08-09 01:19
> It should trigger on LOW.
> 
> Leo

Mmm, but the sensor shows TRIGGERED when there is filament inside. So...

Creality may have changed the filament sensor type in recent batches.

**Comment by leofaoro** [comment] 2022-08-09 01:58
> Mmm, but the sensor shows TRIGGERED when there is filament inside. So...

In the Klipper config for the E3S1 it's triggered = low.

**Comment by sammcj** [comment] 2023-03-18 13:04
FYI for anyone that stumbles across this historical information - the updated version of this controller board as found in the Ender 3 S1 and Ender 5 S1 printers is almost identical but has the model `CR4NS200141C13` and uses a `STM32F401` (RET6), otherwise looks pretty much the same:

![IMG_8946](https://user-images.githubusercontent.com/862951/226108008-5d745820-45f7-48e1-8dcc-001bad3db049.jpeg)

And a similar, but different LCD:

![IMG_8936](https://user-images.githubusercontent.com/862951/226108156-6d3c95ac-d0f9-44a8-822a-5332a6d0e8a6.jpeg)

**Comment by Muravey2** [comment] 2025-09-07 04:41
please help! I can't find the diagram of this board (cr4Ns200141c13). Can anyone tell me if there is a diagram or what name should I specify in the klipper for the j713 connector?
