### ISSUE TITLE
[FR] CR10S_Pro configuration request 

### ISSUE THREAD

**Issue by xtronics** [MarlinFirmware/Configurations#446] opened 2021-03-26 00:23 UTC
### Description

CR10S_Pro  (not to be confused with the CR10S or CR10S_Pro_V2 )

* Manufacturer: Creality
* Model: CR10S_Pro
* Motherboard:  I think this is a 2560

#### Additional Information
Creality has source code - but it won't build via makefile - nor will it build via Arduino IDE - the Configuration.h file is not compatible with the newer Marlin -  There are way to many things in the new configuration.h file that I don't know what to set to.

I think it is possible that the LCD that comes with the CR10S_Pro is not compatible with the current Marlin? (I don't know)  - even so - if there isn't a config - a folder with instead a readme telling owners they have a problem would be a good thing. 

As an aging compute guy - I found getting to the point of building this on Linux extremely tedious - a simple bash scrip that gives a list of packages needed to be installed - and then runs a command to compile would be sweet.  

* Provide links to the requested printer/configuration.

**Comment by ellensp** [comment] 2021-03-26 00:33
Link to firmware source?, as it will provide clues.

**Comment by ellensp** [comment] 2021-03-26 00:40
Link to firmware https://forums.creality3dofficial.com/download/cr-series/cr-10s-pro/

**Comment by xtronics** [comment] 2021-03-26 01:02
That link is older - there is a version at https://file2-cdn.creality.com//website/bc8a9040-e119-47f3-90fb-f87f8c0afa3c

This link may be temporary - if it dosen't work - try https://www.creality.com/download - go to the second page of CR printers - you will see CR10S_pro..

**Comment by ellensp** [comment] 2021-03-26 03:06
please update the tittle.

**Comment by ellensp** [comment] 2021-03-26 03:27
Some motherboard images (same a cr10 max)
<img src="https://cdn.shopify.com/s/files/1/1834/5761/products/1_d5d5825d-ed5a-472e-a8cc-199f2cbb3af9.jpg" >
<img src="https://cdn.shopify.com/s/files/1/1834/5761/products/4_d54a1ab1-7f66-4727-8d0c-5ccd895c97a3_1600x.jpg" >

**Comment by ellensp** [comment] 2021-03-26 03:28
In the base
<img src="https://3dpblog.com/wp-content/uploads/2019/01/cr10spro-power-control.jpg">

**Comment by ellensp** [comment] 2021-03-26 03:33
TFT seems to be same as one as in cr10 max and Ender5 plus
<img src="https://i.stack.imgur.com/O3U4b.jpg">

**Comment by xtronics** [comment] 2021-03-27 06:49
It has auto leveling features (5 zone manual adjust and a 36? point auto level routine) 
and filament detector if that helps? 
https://preview.redd.it/g54yf1xuo8g21.png?width=2560&format=png&auto=webp&s=79cd8559ca78639a782abc415157683318708693

**Comment by thinkyhead** [comment] 2022-04-10 14:35
Duplicate of #649

**Closed as completed by thinkyhead** 2022-04-10 14:35 UTC
