### ISSUE TITLE
Firmware 2.0.9.2 compatibility with 3D pad 5 inch of creality. 

### ISSUE THREAD

**Issue by Flannix** [MarlinFirmware/Configurations#655] opened 2022-01-10 19:02 UTC
### Description

Cant seems to connect to the creality 3d max 
I updated the 3d pad to the last firmware on the creality website. 
The Firmware on the printer is 2.0.9.2

### Configuration Details

* Manufacturer: creality
* Model: ender 3 max
* Motherboard: 4.2.2

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by thinkyhead** [comment] 2022-01-26 19:48
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:48 UTC
