### ISSUE TITLE
[FR] For SKR boards, a BLTouch version and without version.

### ISSUE THREAD

**Issue by aldaw** [MarlinFirmware/Configurations#624] opened 2021-11-24 22:59 UTC
### Description

I have downloaded the configs for crealtiy cr-10 mini but had many problems.
In the end I realized, there is only one config for BLTouch users, since i don't have one plugged in I encountered many errors to work trough.
In the official BTT repo for the SKR board there are a version for BLTouch and one for BLTouch-"less".
This would be of course also nice for the Configurations Archive, if one want to be up to date, since BTT is not adding new Marlin versions as often as the official repo does.

Here a linked issue, wich i have already solved.
https://github.com/MarlinFirmware/Configurations/issues/622

### Configuration Details

* Manufacturer: Creality
* Model: CR-10 Mini
* Motherboard: BigTreeTech SKR Mini E3 2.0

**Comment by thinkyhead** [comment] 2022-01-26 19:47
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:47 UTC
