### ISSUE TITLE
[FR] Artillery Genius Pro

### ISSUE THREAD

**Issue by gudvinr** [MarlinFirmware/Configurations#639] opened 2021-12-27 09:07 UTC
### Description

With Artillery Ruby support added via MarlinFirmware/Marlin#23029 (same board used in Sidewinder X2 and Hornet) and configuration added for SWX2 and Hornet via MarlinFirmware/Configurations#597 it makes sense to add configuration for Genius Pro too.

It is not the same as Genius with ABL because Genius uses older board.

### Configuration Details

* Manufacturer: Artillery3D
* Model: Genius Pro
* Motherboard: Artillery Ruby (STM32F401RCT6)

#### Additional Information

Confiuguration for Genius Pro were added in official Artillery3D repo along with configurations for other mentioned machines:  
https://github.com/artillery3d/Configurations/tree/artillery-import-2.0.x

**Comment by thisiskeithb** [comment] 2021-12-27 09:10
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23313

**Closed as completed by thisiskeithb** 2021-12-27 09:10 UTC
