### ISSUE TITLE
[BUG] Compile error Anet A8 example : too many endif in configuration_adv.h

### ISSUE THREAD

**Issue by HuguesDug** [MarlinFirmware/Configurations#628] opened 2021-12-05 15:36 UTC
### Bug Description

When downloading 
marlin-bug-fix_2.0.x 
and 
Configurations-bugfix-2.0.x.zip\Configurations-bugfix-2.0.x\config\examples\Anet\A8

Cannot compile as the compiler report too many #endif.

Line 1331 in configuration_adv.h

### Configuration Files

original files from the github repo. No need to upload, these are the standard files.

### Steps to Reproduce

download from marlin firmware web page the bugfix version and config files that goes with it.
unpack and grad config for Anet A8

Compile with VS code --> Error

**Expected behavior:**

should compile

**Actual behavior:**

In file included from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfigPre.h:56:0,
                 from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfig.h:28,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
c:\users\hugues\3d objects\upgrades a8\marlin-bugfix-2.0.x\marlin\configuration_adv.h:1331:2: error: #endif without #if
 #endif // HAS_LCD_MENU

**Fix**
I deleted the one that was too much (line 1291). It now compiles.

**Comment by thisiskeithb** [comment] 2021-12-05 19:45
Duplicate of #627

**Closed as completed by thisiskeithb** 2021-12-05 19:45 UTC
