### ISSUE TITLE
Part Cooling Problem

### ISSUE THREAD

**Issue by BitschiClaudio** [MarlinFirmware/Configurations#875] opened 2022-12-31 12:49 UTC
Hi Guys,
I have a problem.

Marlin 2.1.2
BTT octopus pro
2 hot ends 2 extruders
2 Part coller fan

Active:
#define REDUNDANT_PART_COOLING_FAN 1  // Index of the fan to sync with FAN 0.
#define FANMUX0_PIN 2
#define FANMUX1_PIN 2

I want both Part_Fan to always be running, at printing.

If extruder 0 is active in pronterface, everything works with 
M106 S
M106 T0/T1 S0-255
but
with active extruder 1 in Pronterface

nothing works..

and they don't start when printing on t1

Does somebody has any idea?

And a new good year

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/10327117/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/10327118/Configuration_adv.txt)

_Originally posted by @BitschiClaudio in https://github.com/MarlinFirmware/Marlin/discussions/22984#discussioncomment-4559697_

**Comment by BitschiClaudio** [comment] 2022-12-31 12:57
gkljl,

**Comment by BitschiClaudio** [comment] 2022-12-31 12:59
shz

**Comment by thisiskeithb** [comment] 2022-12-31 14:19
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/874

**Closed as completed by thisiskeithb** 2022-12-31 14:19 UTC
