### ISSUE TITLE
configuration Display issue 

### ISSUE THREAD

**Issue by Coolest1** [MarlinFirmware/Configurations#527] opened 2021-06-23 01:56 UTC
```
Marlin\src\lcd\extui\dgus\origin\DGUSDisplayDef.cpp:277:1: error: no matches converting function 'GetVariable' to type 'void (*)(struct DGUS_VP_Variable&, void*)'
 };
 ^
In file included from Marlin\src\lcd\extui\dgus\origin\DGUSDisplayDef.cpp:32:0:
Marlin\src\lcd\extui\dgus\origin\../DGUSDisplay.h:76:15: note: candidate is: template<class T, void (* Setter)(float, T), T selector> static void DGUSDisplay::GetVariable(DGUS_VP_Variable&, void*)
   static void GetVariable(DGUS_VP_Variable &var, void *val_ptr) {
               ^~~~~~~~~~~
*** [.pio\build\mega2560\src\src\lcd\extui\dgus\origin\DGUSDisplayDef.cpp.o] Error 1
Marlin\src\lcd\extui\dgus\origin\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_ResumePauseAbort(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\dgus\origin\DGUSScreenHandler.cpp:88:20: error: 'MKSLCD_SCREEN_PAUSE' was not declared in this scope
                    ^~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\extui\dgus\origin\DGUSScreenHandler.cpp:88:20: note: suggested alternative: 'DGUSLCD_SCREEN_POPUP'
         GotoScreen(MKSLCD_SCREEN_PAUSE);
                    ^~~~~~~~~~~~~~~~~~~
                    DGUSLCD_SCREEN_POPUP
*** [.pio\build\mega2560\src\src\lcd\extui\dgus\origin\DGUSScreenHandler.cpp.o] Error 1
========================================================================================= [FAILED] Took 26.52 seconds ========================================================================================= 

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:26.524
==================================================================================== 1 failed, 0 succeeded in 00:00:26.524 ==================================================================================== 
PS C:\Users\User\Desktop\Ender 5 Plus SKR 1.4 Turbo> echo "done" >C:\Users\User\AppData\Local\Temp\ipc
PS C:\Users\User\Desktop\Ender 5 Plus SKR 1.4 Turbo>
```

**Comment by ellensp** [comment] 2021-06-23 02:13
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21576

**Closed as completed by ellensp** 2021-06-23 02:14 UTC
