### ISSUE TITLE
[FR] (Request Configuration for Anycubic 4Max Pro 2.0) 

### ISSUE THREAD

**Issue by Captain-Benjamin** [MarlinFirmware/Configurations#546] opened 2021-07-24 15:17 UTC
### Configuration Details

* Manufacturer: Anycubic
* Model: 4Max Pro 2.0
* Motherboard: Trigorilla 14

#### Additional Information

* Provide links to the requested printer/configuration.
* anycubic.com

**Comment by thinkyhead** [comment] 2022-04-10 12:29
Duplicate of #649

**Closed as completed by thinkyhead** 2022-04-10 12:29 UTC
