### ISSUE TITLE
[FR] CR10S with SKR mini E3 V3.0

### ISSUE THREAD

**Issue by africsnail** [MarlinFirmware/Configurations#629] opened 2021-12-06 23:18 UTC
Manufacturer: Creality
Model: CR10S
Motherboard: SKR mini E3 V3.0

I was able to find configs for E3 V2.0 here, but not for the new 3.0 version. I found some for ender 3 and ender 5 [here](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V3.0/Marlin), but I am not knowledgeable enough to know exactly what changed since the V3.0 and I think that here might be somebody able and willing to do it.

**Comment by thisiskeithb** [comment] 2021-12-07 00:02
We’ll need SKR Mini E3 V3 board support first:

- https://github.com/MarlinFirmware/Marlin/issues/23189

**Comment by thinkyhead** [comment] 2022-01-26 19:47
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:47 UTC
