### ISSUE TITLE
[FR] CR10S Pro V2 Configuration

### ISSUE THREAD

**Issue by Kavci034** [MarlinFirmware/Configurations#650] opened 2022-01-06 19:22 UTC
Hello,  
Can Someone Add a Config for Creality CR10S Pro V2 or  its mainboard  
cant find a good config/fork to use  

### Machine Details  

- Manufacturer: Creality
- Model: CR-10S Pro V2
- Mainboard: Creality V2.4.1
- Touchscreen: DWIN T5UID1

### Extra Information

- Provide links or files for requested printer configuration

**Comment by thinkyhead** [comment] 2022-01-26 19:48
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:48 UTC
