### ISSUE TITLE
[BUG] Creality CR10s v1: Marlin\src\module\temperature.cpp:330:38: error: static assertion failed: PREHEAT_2_TEMP_HOTEND (250) must be less than HEATER_0_MAXTEMP (250) - 15.

### ISSUE THREAD

**Issue by isidorosss** [MarlinFirmware/Configurations#952] opened 2023-06-18 15:23 UTC
When i try to build 2.1.2.1 on VScode, i get the error:
 Marlin\src\module\temperature.cpp:330:38: error: static assertion failed: PREHEAT_2_TEMP_HOTEND (250) must be less than HEATER_0_MAXTEMP (250) - 15.
I'm updating my Creality CR10s to every newer version of Marlin and it's the first time i get this error on the newest version 2.1.2.1.
<!--

`
 *  Executing task: C:\Users\isido\.platformio\penv\Scripts\platformio.exe run 

Processing mega2560 (board: megaatmega2560; platform: atmelavr@~4.0.1; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR (4.0.1) > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
DEBUG: Current (avr-stub) External (avr-stub, simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8glib-HAL @ 0.5.2
|-- Wire @ 1.0
|-- SPI @ 1.0
Building in release mode
Compiling .pio\build\mega2560\src\src\inc\Warnings.cpp.o
Compiling .pio\build\mega2560\src\src\module\temperature.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdFile.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\mega2560\src\src\sd\cardreader.cpp.o
In file included from Marlin\src\module\../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\module\../inc/MarlinConfig.h:28,
                 from Marlin\src\module\../MarlinCore.h:24,
                 from Marlin\src\module\temperature.cpp:30:
Marlin\src\module\temperature.cpp:330:38: error: static assertion failed: PREHEAT_2_TEMP_HOTEND (250) must be less than HEATER_0_MAXTEMP (250) - 15.
     #define CHECK_PREHEAT__(N,P,T,M) static_assert(T <= M - HOTEND_OVERSHOOT, "PREHEAT_" STRINGIFY(P) "_TEMP_HOTEND (" STRINGIFY(T) ") must be less than HEATER_" STRINGIFY(N) "_MAXTEMP (" STRINGIFY(M) ") - " STRINGIFY(HOTEND_OVERSHOOT) ".");
                                      ^
Marlin\src\module\../inc/../core/macros.h:650:24: note: in definition of macro 'EVAL1'
Compiling .pio\build\mega2560\libe7e\U8glib-HAL\clib\u8g_com_atmega_parallel.c.o
 #define EVAL1(V...)    V
                        ^
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:647:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:647:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:646:24: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:647:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
Marlin\src\module\../inc/../core/macros.h:649:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:648:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:647:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:646:30: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                              ^~~~~
Marlin\src\module\../inc/../core/macros.h:637:24: note: in expansion of macro 'EVAL16'
 #define EVAL           EVAL16
                        ^~~~~~
Marlin\src\module\temperature.cpp:331:33: note: in expansion of macro 'CHECK_PREHEAT__'
     #define CHECK_PREHEAT_(N,P) CHECK_PREHEAT__(N, P, PREHEAT_##P##_TEMP_HOTEND, HEATER_##N##_MAXTEMP)
                                 ^~~~~~~~~~~~~~~
Marlin\src\module\../inc/../core/macros.h:689:3: note: in expansion of macro 'CHECK_PREHEAT_'
   _RPT_OP(_RPT_I,V)                                              \
   ^~~~~~~
Marlin\src\module\../inc/../core/macros.h:701:38: note: in expansion of macro '_REPEAT2'
 #define REPEAT2_S(S,N,OP,V...)  EVAL(_REPEAT2(S,SUB##S(N),OP,V))
                                      ^~~~~~~~
Marlin\src\module\../inc/../core/macros.h:702:33: note: in expansion of macro 'REPEAT2_S'
 #define REPEAT2(N,OP,V...)      REPEAT2_S(0,N,OP,V)
                                 ^~~~~~~~~
Marlin\src\module\temperature.cpp:332:30: note: in expansion of macro 'REPEAT2'
     #define CHECK_PREHEAT(P) REPEAT2(HOTENDS, CHECK_PREHEAT_, P)
                              ^~~~~~~
Marlin\src\module\temperature.cpp:337:7: note: in expansion of macro 'CHECK_PREHEAT'
       CHECK_PREHEAT(2)
       ^~~~~~~~~~~~~
*** [.pio\build\mega2560\src\src\module\temperature.cpp.o] Error 1
======================================================================== [FAILED] Took 51.91 seconds ========================================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:51.911
=================================================================== 1 failed, 0 succeeded in 00:00:51.911 ===================================================================

 *  The terminal process "C:\Users\isido\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. `

[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/11781922/Configuration.zip)

**Comment by ellensp** [comment] 2023-06-18 15:28
Not a bug.

read the  message

**Comment by ellensp** [comment] 2023-06-18 15:29
unless your talking abut the marlin provided config...  
checking

**Comment by ellensp** [comment] 2023-06-18 15:34
This is in example Configs.  

https://github.com/MarlinFirmware/Configurations/blob/release-2.1.2.1/config/examples/Creality/CR-10S/CrealityV1/Configuration.h#L2227

#define HEATER_0_MAXTEMP 250
with 
#define PREHEAT_2_TEMP_HOTEND 250
is not valid

**Comment by isidorosss** [comment] 2023-06-18 15:50
> This is in example Configs.
> 
> https://github.com/MarlinFirmware/Configurations/blob/release-2.1.2.1/config/examples/Creality/CR-10S/CrealityV1/Configuration.h#L2227
> 
> #define HEATER_0_MAXTEMP 250 with #define PREHEAT_2_TEMP_HOTEND 250 is not valid

Thank you for the help. Ok, i'm replacing
#define PREHEAT_2_TEMP_HOTEND 250
with
#define HEATER_0_MAXTEMP 250
right?

I'm updating my Creality CR10s to every newer version of Marlin and it's the first time i get this error on the newest version 2.1.2.1.
Will it be fixed on newer releases?

One more thing. I guess i shouldn't open a new issue for this. On Configuration_adv.h , line 1743, i have to enable #define NO_SD_DETECT . I guess this must be global on CR10s and should be fixed on newer releases. Could it be that only my CR10s has an SD extender?


Thanks!

**Comment by ellensp** [comment] 2023-06-18 15:53
no...  Im just documenting the cause 
with #define HEATER_0_MAXTEMP 250 the highest PREHEAT_2_TEMP_HOTEND you can set is 235

**Comment by isidorosss** [comment] 2023-06-18 15:54
ok thanks. i'll wait for a fix then.

**Comment by isidorosss** [comment] 2023-07-27 13:04
Anyone? Any suggestions?

**Comment by thisiskeithb** [comment] 2023-07-27 13:06
> Anyone? Any suggestions?

Change `PREHEAT_2_TEMP_HOTEND` from `250` to `235`.

**Comment by thisiskeithb** [comment] 2023-07-27 15:24
This is already fixed in `bugfix-2.1.x` and will be fixed in the next tagged release:

https://github.com/MarlinFirmware/Configurations/blob/b2667913e78ac78bf3ada855fe3b2f6cbfe7cf64/config/examples/Creality/CR-10S/CrealityV1/Configuration.h#L2372

**Closed as completed by thisiskeithb** 2023-07-27 15:24 UTC
Labels: bug
