### ISSUE TITLE
[FR] Config with powerstep01 (or X-NUCLEO-IHM03A1) on Mega2560, Due, or Nucleo-F767ZI

### ISSUE THREAD

**Issue by mikhail11111** [MarlinFirmware/Configurations#665] opened 2022-01-21 20:01 UTC
### Configuration Details

* Manufacturer:
* Model:
* Motherboard:

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by ellensp** [comment] 2022-01-23 01:39
POWERSTEP01 is already supported
/**
 * Stepper Drivers
 *
 * These settings allow Marlin to tune stepper driver timing and enable advanced options for
 * stepper drivers that support them. You may also override timing options in Configuration_adv.h.
 *
 * A4988 is assumed for unspecified drivers.
 *
 * Use TMC2208/TMC2208_STANDALONE for TMC2225 drivers and TMC2209/TMC2209_STANDALONE for TMC2226 drivers.
 *
 * Options: A4988, A5984, DRV8825, LV8729, L6470, L6474, POWERSTEP01,     <======== see

**Comment by mikhail11111** [comment] 2022-01-23 05:00
The problem is there is no configuration file with POWERSTEP01 in the examples. When I simply insert it instead of A4988 in the default configuration, it doesn't compile with multiple errors.

**Comment by ellensp** [comment] 2022-01-23 05:33
You need to define the pins it uses and a macro
eg for RAMPS

```CPP
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_RAMPS_14_EFB
  #define L6470_CHAIN_SCK_PIN 53
  #define L6470_CHAIN_MISO_PIN 49
  #define L6470_CHAIN_MOSI_PIN 40
  #define L6470_CHAIN_SS_PIN 42
  /**
   * Macro to reset/enable L6474 stepper drivers
   *
   * IMPORTANT - To disable (bypass) L6474s, install the corresponding
   *             resistors (R11 - R17) and change the "V" to "0" for the
   *             corresponding pins here:
   */
  #define ENABLE_RESET_L64XX_CHIPS(V)   do{ OUT_WRITE(X_ENABLE_PIN, V); \
                                          OUT_WRITE(Y_ENABLE_PIN, V); \
                                          OUT_WRITE(Z_ENABLE_PIN, V); \
                                          OUT_WRITE(E0_ENABLE_PIN,V); \
                                          OUT_WRITE(E1_ENABLE_PIN,V); \
                                        }while(0)
#endif
```

**Comment by ellensp** [comment] 2022-01-23 05:43
I don't know what that comment is in referees to, macro is adapted form Marlin/src/pins/stm32f4/pins_STEVAL_3DP001V1.h 
Comment may be motherboard related.

**Comment by mikhail11111** [comment] 2022-01-25 20:26
Now it compiles but still there is no SPI communication with the driver. I suppose the problem is that it needs some additional pins set (probably the Reset and Step clock), but I couldn't find where to do that.

**Comment by ellensp** [comment] 2022-01-26 00:48
The reset is using that macro, and uses the enable pins.

**Comment by mikhail11111** [comment] 2022-01-30 15:31
Right, but still something is missing, not sure what. 
I've been using Marlin only in step-dir mode so far; is there something I might be missing that is pertinent to SPI mode? I connected the SCK, MOSI, MISO, CS.

**Comment by thinkyhead** [comment] 2022-04-10 12:32
Duplicate of #649

**Closed as completed by thinkyhead** 2022-04-10 12:32 UTC

**Comment by Bob-the-Kuhn** [comment] 2022-06-19 23:00
The other item that neeeds to be defined is **_CHAIN_POS** for each powerStep.

FYI - I found the TMC5160 to be a superior driver.  I wouldn't mind seeing the L64xx series drivers disapear from Marlin.
