### ISSUE TITLE
[BUG] (SD problem on skr pro V1.2)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Configurations#653] opened 2022-01-10 09:15 UTC
Hello
Marlin 2.0.9.3 doesn't show the file on the SD card
I use BTT SKR PRO V1.2 as motherboard and generic delta configuration for delta printer
I have enabled enabled SDSUPPORT and SD_CHECK_AND_RETRY but when I click on "print from media" It doesn't show the file on SD card
there are g-codes on SD card 

here are the pictures

![4072e0f8-073e-42e5-95a4-1dae2a565fb6](https://user-images.githubusercontent.com/75531691/148741239-d57c3b4d-8a8d-42be-bacd-f50e2c44f63f.jpg)
![21be5658-901c-4eb9-a877-0d38af00b334](https://user-images.githubusercontent.com/75531691/148741259-467eef29-2b8d-4fba-8db3-00c5c2259c9f.jpg)
![bc719171-50ee-4a69-9e95-a82219bc5a7c](https://user-images.githubusercontent.com/75531691/148741274-d199fdd0-e42b-4a44-a29b-36c2814f2c1e.jpg)
d

**Comment by thisiskeithb** [comment] 2022-01-25 17:03
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23617

**Closed as completed by thisiskeithb** 2022-01-25 17:03 UTC
