### ISSUE TITLE
[FR] (x-nucleo-ihm03a1 configuration)

### ISSUE THREAD

**Issue by mikhail11111** [MarlinFirmware/Configurations#674] opened 2022-02-08 08:50 UTC
### Description

Configuration for x-nucleo-ihm03a1 driver

### Configuration Details

x-nucleo-ihm03a1 is a board with powerstep01 driver, which is included in Marlin, but I've been unsuccessful to make it work. 
It has Arduino Uno interface so any such board can be used. 

* Manufacturer: ST
* Model: x-nucleo-ihm03a1
* Motherboard: any Arduino compatible

#### Additional Information

* Provide links to the requested printer/configuration.
* https://www.st.com/en/ecosystems/x-nucleo-ihm03a1.html#tools-software

**Comment by ellensp** [comment] 2022-02-09 02:38
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/665

**Closed as completed by ellensp** 2022-02-09 02:38 UTC
