### ISSUE TITLE
[FR] Add support for Anet E12

### ISSUE THREAD

**Issue by andramadon** [MarlinFirmware/Configurations#203] opened 2020-09-04 19:42 UTC
There is support for the E10 and the E16 but not for the E12. Im not sure if i can just use either of those. I dont mean to noob it up. all of this code can be a bit intimidating.

**Comment by thinkyhead** [comment] 2020-10-06 07:14
Those might be a good starting point, but get tips from other users. And if you end up with a good config please submit it here!

**Comment by Vertabreak** [comment] 2021-02-19 01:46
if someone with the printer where to contact me and be willing to do some testing im sure i could get this ported over to marlin 2.0.x.
if some existing older version can be provided that would speed along the process.
i can be reached on the marlin discord username vert with a blue name/role should someone wish to explore getting this done.
upon completion like most of my work i will contribute it back to upstream marlin making it available to everyone.
porting over printers from older versions of marlin is kinda my thing Ive ported over more then 20 printers.
donations for this work is appreciated but not required but it is a great motivator given the time invested.

**Comment by Surfer2go** [comment] 2021-02-27 19:24
Hi I have  a Anet E12 Printer runing with Marlin. If you need something Tested....., I´m Running a SKR 1.4 Turbo with TMC2130SPI
Very smooth!!

**Comment by thinkyhead** [comment] 2022-04-10 12:30
Duplicate of #649

**Closed as completed by thinkyhead** 2022-04-10 12:30 UTC
