### ISSUE TITLE
[FR] Ender-3 with Creality touchscreen (4.2.7 board)

### ISSUE THREAD

**Issue by eagle00789** [MarlinFirmware/Configurations#554] opened 2021-08-15 00:57 UTC
there should be a working config for the ender 3 with 4.2.7 board with support for the newly released touchscreen (based on the CR-6 also without rotary encoder)
The touchscreen is mentioned [here](https://www.creality3dofficial.com/collections/accessories/products/upgraded-touch-panel-screen-display-for-ender-3-pro-ender-3-v2) and this page mentions the new touchscreen with 4.2.7 support based on DWIN

**Comment by thisiskeithb** [comment] 2021-08-16 19:22
That TFT is not supported in Marlin currently, but will once https://github.com/MarlinFirmware/Marlin/pull/19958 is merged.

**Comment by thinkyhead** [comment] 2021-10-30 06:00
That PR has been stalled pending testing. I have a CR-6 SE I can play around with here, so I will make a special effort to get that merged soon.

**Comment by thinkyhead** [comment] 2022-04-10 14:35
Duplicate of #649

**Closed as completed by thinkyhead** 2022-04-10 14:35 UTC

**Comment by dhysuiej** [comment] 2023-10-21 20:17
@eagle00789 I'm also interested in this. Mine has the 4.2.2 board. Did you manage to get the CR-6 touch screen working on Ender 3 running Marlin.
