### ISSUE TITLE
[FR] (configuration request title)

### ISSUE THREAD

**Issue by curiousmongrel** [MarlinFirmware/Configurations#673] opened 2022-02-07 23:16 UTC
### Description

Configuration for Ender 3V2 4.2.7 board

### Configuration Details

* Manufacturer:  Creality
* Model: Ender 3V2
* Motherboard: 4.2.7

#### Additional Information

* Provide links to the requested printer/configuration.

*https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2

**Comment by ellensp** [comment] 2022-02-07 23:57
1) Never ever use import branch. it is for developers for updating configs
Use the version of config that is for the version of the code you are using.
Ie if using bugfix, use bugfix, if release, use the release   
It even says what version to use in your config/README.md file. 

2) To change from 4.2.2. to 4.2.7 you change one line. That is it.
  #define MOTHERBOARD BOARD_CREALITY_V4 becomes   #define MOTHERBOARD BOARD_CREALITY_V427

**Comment by ellensp** [comment] 2022-02-07 23:58
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/649

**Closed as completed by ellensp** 2022-02-07 23:58 UTC
