### ISSUE TITLE
[FR] Creality CR10S Pro V2

### ISSUE THREAD

**Issue by chappy1978** [MarlinFirmware/Configurations#521] opened 2021-06-13 18:58 UTC
Can you please add a config for a Creality CR10S Pro V2?
Thank You

### Configuration Details

* Manufacturer:
* Model:
* Motherboard:

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by thinkyhead** [comment] 2021-06-13 21:06
Someone with the hardware will have to get it sorted out. If you manage to produce working configs, please submit!

**Comment by LTSpenny** [comment] 2021-06-22 06:39
@thinkyhead new to GitHub how do we submit configs?

**Comment by LTSpenny** [comment] 2021-06-22 06:53
@thinkyhead belay my last. Just found info on how to do so.

**Comment by burnsy180** [comment] 2021-08-09 01:13
Has there been any progress on this configuration please? @LTSpenny have you got a working config you can share?

**Comment by SushiKiIIer** [comment] 2021-11-18 08:01
I need a set of config files as well; or a link to a guide for setting one up from scratch and ill give it a try xD. Doesn't look like the forum above is actually filled out so in case it helps someone get the config file sorted ill do it. Sorry if the links aren't to technical pages for the boards  I haven't been able to find much so far info wise.

thanks again


       **Description:**   CR-10S Pro V2 Stock configuration files ( *h & adv*h )

**Configuration details:**
          - Manufacturer: Creality
          - Model: CR-10S Pro V2
          - Motherboard: Creality V2.4.1

**Additional Information**
          - Printer Link: CR-10SProV2: https://tiny-machines-3d.myshopify.com/products/cr10sprov2?_pos=3&_sid=74ca44ec2&_ss=r
          - Motherboard Link: Creality V2.4.1: https://tiny-machines-3d.myshopify.com/products/creality-10s-pro-motherboard

**Comment by thinkyhead** [comment] 2022-01-26 19:47
Duplicate of #649

**Closed as completed by thinkyhead** 2022-01-26 19:47 UTC
Labels: help wanted
